#ifndef _MVS_SLIST_DEFS_
#define _MVS_SLIST_DEFS_

typedef enum mSlistCommand_t mSlistCommand_t;

enum mSlistCommand_t {
		MVS_SLIST_COMMAND_MAKE_ENTITY,
		MVS_SLIST_COMMAND_MAKE_CONSTANT,
		MVS_SLIST_COMMAND_MAKE_CONFIG,
		MVS_SLIST_COMMAND_USE_ENTITY_CONFIG,
		MVS_SLIST_COMMAND_REGISTER_CONF,
		MVS_SLIST_COMMAND_SET_INSTANCE_COUNT,
		MVS_SLIST_COMMAND_SET_ARGS,
		MVS_SLIST_COMMAND_SET_CONFIG,
		MVS_SLIST_COMMAND_SET_PROPERTY,
		MVS_SLIST_COMMAND_SET_ELIM,
		MVS_SLIST_COMMAND_SET_SETUP,
		MVS_SLIST_COMMAND_SET_FLAG,
		MVS_SLIST_COMMAND_SET_ADD_TO_LOCAL_LIST,
};

#endif
