#ifndef _MVS_INTERFACE_TYPES_
#define _MVS_INTERFACE_TYPES_

typedef enum mInterface_t mInterface_t;

enum mInterface_t {
  MINTERFACE_TYPE_FILE,
  MINTERFACE_TYPE_PIPE,
  MINTERFACE_TYPE_MAPPED_MEMORY,
  MINTERFACE_TYPE_MAPPED_FILE,
  MINTERFACE_TYPE_DYNAMIC_LIBRARY,
  MINTERFACE_TYPE_LIMIT
};

#endif
