#ifndef _MERRY_REGISTERS_
#define _MERRY_REGISTERS_

typedef enum mcorereg_t mcorereg_t;

// Get this shit somehow
enum mcorereg_t {
  MERRY_CORE_R0,
  MERRY_CORE_R1,
  MERRY_CORE_R2,
  MERRY_CORE_R3,
  MERRY_CORE_R4,
  MERRY_CORE_R5,
  MERRY_CORE_R6,
  MERRY_CORE_R7,
  MERRY_CORE_R8,
  MERRY_CORE_R9,
  MERRY_CORE_R10,
  MERRY_CORE_R11,
  MERRY_CORE_R12,
  MERRY_CORE_R13,
  MERRY_CORE_R14,
  MERRY_CORE_R15,
  MERRY_CORE_REG_COUNT
};

#endif
