#ifndef _MVS_GRAVES_CONSTANTS_
#define _MVS_GRAVES_CONSTANTS_

#define _MVS_CONSTANT_ENTITY_COUNT_ 10 // just a mock number
#define _MVS_CONSTANT_REQUEST_QUEUE_INITIAL_LENGTH_ 20
#define _MVS_CONSTANT_REQUEST_RESULT_ARRAY_LEN_ 3
#define _MVS_CONSTANT_ENTITY_LIST_INITIAL_LEN_ 5

#endif
