#ifndef _MERRY_CORE_DEFS_
#define _MERRY_CORE_DEFS_

#define _MERRY_CORE_PAGE_LEN_IN_BYTES_ 32768 // 32KB
#define _MERRY_CORE_STACK_LEN_ 1048576       // 1MB
#define _MERRY_CORE_CALL_DEPTH_ 50

#endif
